### ISSUE TITLE
TargetID numbers

### ISSUE THREAD

**Issue by miyho** [Hypnootize/Deli-Hud#1]
Is there anything i can do to make the outline smoother or make the targetid numbers have shadows? I play medic and it takes me too much time to read the health (my visions isnt that good so the outline doesnt help it), wich draws too much time for me and i often die on HL matches because my eyes are looking at other places. I really dont want to change huds so pls consider fix :steamhappy: 
![image](https://github.com/Hypnootize/Deli-Hud/assets/87745343/2c70f920-5ffe-446c-9246-2fdffc4afc81)

**Comment by miyho** [comment]
oh btw the freezecam enemy health number shadow is white instead of black

**Comment by Hypnootize** [comment]
You can't make the outline smoother sadly but you can use the shadow instead, inside `Resource/UI/SpectatorGUIHealth.res`  make both `"PlayerStatusHealthValueTarget"` and `"PlayerStatusHealthValueTargetShadow"` use `"M0refont14"` as their `"font"` and then set the `visible` back to `1` for `"PlayerStatusHealthValueTargetShadow"`

I'll try to fix the white shadow for the freezepanel later!

**Comment by miyho** [comment]
tysm

**Comment by miyho** [comment]
@Hypnootize i made the shadow closer to the numbers as it was still discomfortable and chaged the font because the "m0refont14" didnt work, ended up like this

![image](https://github.com/Hypnootize/Deli-Hud/assets/87745343/3ebc4b07-2294-4581-944c-c98141e382aa)

i think it looks really good and more readable, so... update? =D

**Comment by Hypnootize** [comment]
The freezecam animation bug it's fixed as for the target health it's been like this since forever so I don't really feel like changing it as I'm not the HUD creator, I'd like to keep this version as close as it originally was. 
If should check out deli reborn or neue for more refined versions, you can find them [here ](https://github.com/Hypnootize/TF2-HUDs-Archive/blob/master/Updated%20HUDs%20List.md)
